spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: CommentService-DB

  application:
    name: comment-service

eureka:
  client:
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
server:
  port: 3015
  management:
    endpoints:
      web:
        exposure:
          include:
            - "*"
      endpoint:
        health:
          show-details: always